apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: flywheel-pending-index-logs-recovery
  namespace: default
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: curl:v1.0.0
            command:
            - curl
            - -v
            - http://flywheel/v1/
          restartPolicy: Never